// import { explainRecommendation } from "./llm.js";

const wikidataUrl = "https://query.wikidata.org/sparql";

// Récupération de l'ID depuis le Session Storage
let movieSelected = JSON.parse(sessionStorage.getItem("moviesClick")) || [];
if (movieSelected.length > 0) {
  sessionStorage.setItem("moviesClick", JSON.stringify(movieSelected));
}

console.log(movieSelected);
// Fonction pour afficher les détails dans les divs
async function displayFilmDetails(movieSelected) {
  const imageDiv = document.getElementById("imageFilm");
  const titleDiv = document.getElementById("titleFilm");
  const genreDiv = document.getElementById("genreFilm");
  const directorDiv = document.getElementById("director");
  const descriptionDiv = document.getElementById("descriptionFilm");
  const yearDiv = document.getElementById("yearFilm");
  const IASummary = document.getElementById("IASummary");

  if (imageDiv) {
    if (movieSelected.image) {
      imageDiv.style.display = "flex";
      imageDiv.innerHTML = `<img src="${movieSelected.image}" alt="${movieSelected.title}"/>`;
    } else {
      imageDiv.style.display = "none";
      imageDiv.innerHTML = "";
    }
  }
  // Affiche le titre
  titleDiv.innerHTML = `<p>${movieSelected.title}</p>`;
  directorDiv.innerHTML = `<p><strong>Réalisateur :</strong> ${movieSelected.directorName}</p>`;

  // Affiche le genre
  if (movieSelected.genresLabels && movieSelected.genresLabels.length > 0) {
    let htmlGenre = "<p><strong>Genres :</strong>";

    movieSelected.genresLabels.slice(0, 5).forEach((e) => {
      htmlGenre += `<div class='genre-bubble'>${e}</div>`;
    });

    htmlGenre += "</p>";
    genreDiv.innerHTML = htmlGenre;
  } else {
    genreDiv.innerHTML = "<p><strong>Genre :</strong> Non spécifié</p>";
  }

  // Affiche la description
  if (movieSelected.description) {
    descriptionDiv.innerHTML = `
    <div id='IADiv'>
    <p><strong>Description : </strong></p>
    </div>
    <p>${movieSelected.description}</p>
    `;
  } else {
    descriptionDiv.innerHTML = "<p>Description non disponible</p>";
  }

  // Affiche l'année de sortie
  if (movieSelected.year) {
    yearDiv.innerHTML = `<p>${movieSelected.year}</p>`;
  } else {
    yearDiv.innerHTML = "<p>Année de sortie non disponible</p>";
  }

  // Affiche l'explication IA s'il y en a une
  let explicationIA = "Recommandé car similaire à ....";
  if (movieSelected.isRecommended)
  {
      summaryFilm.style.display = "flex";
      summaryFilm.innerHTML = summaryFilm.innerHTML + `
        <div class='panelInfos' id="IASummary">
          <div id='IADiv'>
          <p><strong>Explication recommandation</strong></p>
          <img src="ia_sparks.svg" alt"Generated by IA" class="ia-icon"/>    
          </div>
          <p>${explicationIA}</p>
        </div>
`;
  }

  // // Affiche l'explication IA
  // if (movieSelected.isRecommended) {
  //   try {
  //     let savedMovies = JSON.parse(sessionStorage.getItem("moviesUsed")) || [];
  //     const explanation = await explainRecommendation({
  //       filmsUtilisateur: savedMovies,
  //       filmRecommande: movieSelected,
  //       analyseRecommandation: {
  //         scoreTotal: 7,
  //         raisons: {
  //           realisateurCommun: {
  //             points: 0,
  //             details: [],
  //           },
  //           genresCommuns: {
  //             points: 0,
  //             details: [],
  //           },
  //           acteursCommuns: {
  //             points: 0,
  //             details: [],
  //           },
  //           anneeProche: {
  //             points: 1,
  //             ecart: 14,
  //           },
  //           paysCommun: {
  //             points: 0,
  //             details: [],
  //           },
  //           scenaristeCommun: {
  //             points: 0,
  //             details: [],
  //           },
  //           motsClesCommuns: {
  //             points: 0,
  //             details: [],
  //           },
  //           langueCommune: {
  //             points: 0,
  //             details: [],
  //           },
  //           dureeProche: {
  //             points: 1,
  //             ecart: 7,
  //           },
  //           prixRecompenses: {
  //             points: 3,
  //             details: "Les trois films ont été primés aux Oscars",
  //           },
  //           innovationVisuelle: {
  //             points: 2,
  //             details: "Style visuel distinctif et mémorable",
  //           },
  //         },
  //       },
  //     });
  //     IASummary.innerHTML = `<p>${explanation}</p>`;
  //   } catch (error) {
  //     IASummary.innerHTML = "<p>Explication non disponible</p>";
  //     console.error(
  //       "Erreur lors de la génération de l'explication IA :",
  //       error
  //     );
  //   }
  // }
}

displayFilmDetails(movieSelected);
