import { explainRecommendation } from "./llm.js";

const wikidataUrl = "https://query.wikidata.org/sparql";

// Récupération de l'ID depuis le Session Storage
let movieSelected = JSON.parse(sessionStorage.getItem("moviesClick")) || [];
if (movieSelected.length > 0) {
  sessionStorage.setItem("moviesClick", JSON.stringify(movieSelected));
}

console.log(movieSelected);

// Fonction pour afficher les détails dans les divs
async function displayFilmDetails(movieSelected) {
  const imageDiv = document.getElementById("imageFilm");
  const titleDiv = document.getElementById("titleFilm");
  const genreDiv = document.getElementById("genreFilm");
  const directorDiv = document.getElementById("director");
  const descriptionDiv = document.getElementById("descriptionFilm");
  const yearDiv = document.getElementById("yearFilm");
  const summaryFilm = document.getElementById("summaryFilm");

  if (imageDiv) {
    if (movieSelected.image) {
      imageDiv.style.display = "flex";
      imageDiv.innerHTML = `<img src="${movieSelected.image}" alt="${movieSelected.title}"/>`;
    } else {
      imageDiv.style.display = "none";
      imageDiv.innerHTML = "";
    }
  }

  // Affichage des informations de base
  titleDiv.innerHTML = `<p>${movieSelected.title}</p>`;
  directorDiv.innerHTML = `<p><strong>Réalisateur :</strong> ${movieSelected.directorName}</p>`;

  // Affichage des genres
  if (movieSelected.genresLabels && movieSelected.genresLabels.length > 0) {
    let htmlGenre = "<p><strong>Genres :</strong>";
    movieSelected.genresLabels.slice(0, 5).forEach((e) => {
      htmlGenre += `<div class='genre-bubble'>${e}</div>`;
    });
    htmlGenre += "</p>";
    genreDiv.innerHTML = htmlGenre;
  } else {
    genreDiv.innerHTML = "<p><strong>Genre :</strong> Non spécifié</p>";
  }

  // Affichage de la description
  if (movieSelected.description) {
    descriptionDiv.innerHTML = `
            <div id='IADiv'>
                <p><strong>Description : </strong></p>
            </div>
            <p>${movieSelected.description}</p>
        `;
  } else {
    descriptionDiv.innerHTML = "<p>Description non disponible</p>";
  }

  yearDiv.innerHTML = `<p>${movieSelected.year || "Année non disponible"}</p>`;

  if (movieSelected.isRecommended) {
    summaryFilm.style.display = "flex";

    summaryFilm.innerHTML += `
            <div class='panelInfos' id="IASummary">
                <div id='IADiv'>
                    <p><strong>Explication recommandation</strong></p>
                    <img src="ia_sparks.svg" alt="Generated by IA" class="ia-icon"/>    
                </div>
                <p id="streamingText"></p>
            </div>`;

    const textContainer = document.getElementById("streamingText");

    if (movieSelected.cachedExplanation) {
      console.log("Explication récupérée depuis l'attribut du film.");
      textContainer.innerText = movieSelected.cachedExplanation;
      return;
    }

    try {
      console.log("Démarrage de la recommandation IA...");
      textContainer.innerHTML = "<em>L'IA analyse votre profil...</em>";

      let savedMovies = JSON.parse(sessionStorage.getItem("moviesUsed")) || [];

      const stream = await explainRecommendation({
        filmsUtilisateur: savedMovies,
        filmRecommande: movieSelected,
        analyseRecommandation: {
          scoreTotal: movieSelected.recommendation.score,
          raisons: movieSelected.recommendation.reasons,
        },
      });

      let fullText = "";
      textContainer.innerText = "";

      for await (const chunk of stream) {
        const content = chunk.choices[0]?.delta?.content || "";
        fullText += content;
        textContainer.innerText = fullText;
      }

      movieSelected.cachedExplanation = fullText;
      sessionStorage.setItem("moviesClick", JSON.stringify(movieSelected));
      console.log("Explication sauvegardée dans l'objet movieSelected.");
    } catch (error) {
      console.error("Erreur streaming :", error);
      textContainer.innerText = "Erreur de génération.";
    }
  }
}

displayFilmDetails(movieSelected);
